### ISSUE TITLE
Error uploading UK LERCs spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#588]
layer id: 110
script: UK_LERCS

The layer looks okay in geoserver but I got the following error, which I think is because there are spaces in the short name of the layer.

Error:
Load layer into geoserver
Creating layer in geoserver...
java.lang.IllegalArgumentException: Illegal character in path at index 56: https://layers.nbnatlas.org/geoserver/rest/layers/ALA:UK LERCs June 2018
	at java.net.URI.create(URI.java:859)
	at org.apache.http.client.methods.HttpPut.<init>(HttpPut.java:68)
	at au.org.ala.layers.ingestion.PostgisTableGeoserverLoader.load(PostgisTableGeoserverLoader.java:81)
	at au.org.ala.layers.ingestion.PostgisTableGeoserverLoader.main(PostgisTableGeoserverLoader.java:50)
Caused by: java.net.URISyntaxException: Illegal character in path at index 56: https://layers.nbnatlas.org/geoserver/rest/layers/ALA:UK LERCs June 2018
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at java.net.URI.create(URI.java:857)
	... 3 more

**Comment by sophiathirza** [comment]
Should I reupload removing the spaces in the short name?

**Comment by reupost** [comment]
Yes, that's correct. I've cleaned out the database and reloaded it, though I needed to manually fix the name in Geoserver as well for some reason. It is now visible.

**Comment by sophiathirza** [comment]
Brilliant - thanks.
