### ISSUE TITLE
Error uploading spatial layer

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#603]
Layer id:111
Script: osni_county_boundaries.sh

Error:
Reading line 18, statement 12
Checking row count of shape geometry table
Creating layers table entry...
Creating fields table entry...
Create objects from layer
Connecting to database
Reading field sid, name and description...
java.lang.RuntimeException: No fields table entry for layer, or objects have already been created for all fields table entries for layer.
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.create(ContextualObjectCreator.java:68)
	at au.org.ala.layers.ingestion.contextual.ContextualObjectCreator.main(ContextualObjectCreator.java:24)

**Comment by sophiathirza** [comment]
I get the same error for

Layer id: 112
Script: SWT_reserves.sh

**Comment by sophiathirza** [comment]
Closing, both layers are detailed in other issues (#642 and #553)
